import os

code = []
code.append('using System;')
code.append('using System.IO;')
code.append('using System.Text;')
code.append('using Newtonsoft.Json;')
code.append('using SwitchMonitor.Common;')
code.append('using SwitchMonitor.Data;')
code.append('')
code.append('namespace SwitchMonitor.Tests')
code.append('{')
code.append('    public class AlarmThresholdTests')
code.append('    {')
code.append('        static int p = 0;')
code.append('        static int f = 0;')
code.append('')
code.append('        public static (int passed, int failed) RunAll()')
code.append('        {')
code.append('            Console.OutputEncoding = Encoding.UTF8;')
code.append('            Console.WriteLine();')
code.append('            Console.WriteLine("=== Slice 8-Alarm: alarm threshold config tests ===");')
code.append('            Console.WriteLine();')
code.append('            T1(); T2(); T3(); T4(); T5(); T6(); T7(); T8(); T9(); T10();')
code.append('            Console.WriteLine();')
code.append('            Console.WriteLine("=== Slice 8-Alarm results ===");')
code.append('            Console.WriteLine("Passed: {0}, Failed: {1}", p, f);')
code.append('            return (p, f);')
code.append('        }')
code.append('')
code.append('        static void T1() {')
code.append('            Console.WriteLine("--- Cycle 1a: model creation ---");')
code.append('            try {')
code.append('                var c = new PhaseThresholdConfig { Enabled = true, UpperLimit = 2.0f, UpperColor = "#FF0000", UpperLineStyle = "dash" };')
code.append('                A(c.Enabled, "Enabled"); A(c.UpperLimit == 2.0f, "UpperLimit");')
code.append('                var cfg = new AlarmThresholdConfig {')
code.append('                    Current = new PhaseThresholdConfig { Enabled = true, UpperLimit = 2.0f, UpperColor = "#FF0000", UpperLineStyle = "dash" },')
code.append('                    Power = new PhaseThresholdConfig { Enabled = true, UpperLimit = 1.5f, UpperColor = "#FF0000", UpperLineStyle = "dash" }')
code.append('                };')
code.append('                A(cfg.Current != null, "Current not null");')
code.append('                A(cfg.Power != null, "Power not null");')
code.append('                Console.WriteLine("  [PASS] Cycle 1a"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T2() {')
code.append('            Console.WriteLine("--- Cycle 1b: JSON round trip ---");')
code.append('            try {')
code.append('                var cfg = new AlarmThresholdConfig {')
code.append('                    Current = new PhaseThresholdConfig { Enabled = true, UpperLimit = 3.5f, UpperColor = "#FF4500", UpperLineStyle = "solid" },')
code.append('                    Power = new PhaseThresholdConfig { Enabled = false, UpperLimit = 2.0f, UpperColor = "#DC143C", UpperLineStyle = "dash" }')
code.append('                };')
code.append('                string json = cfg.ToJson();')
code.append('                A(json.Contains("alarmThresholds"), "JSON has alarmThresholds");')
code.append('                var deser = AlarmThresholdConfig.FromJson(json);')
code.append('                A(deser != null, "deserialized not null");')
code.append('                A(deser.Current.UpperLimit == 3.5f, "round-trip Current.UpperLimit");')
code.append('                A(deser.Power.Enabled == false, "round-trip Power.Enabled");')
code.append('                Console.WriteLine("  [PASS] Cycle 1b"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T3() {')
code.append('            Console.WriteLine("--- Cycle 2a: defaults ---");')
code.append('            try {')
code.append('                string tp = Path.Combine(Path.GetTempPath(), "at1.json");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                var mgr = new ConfigManager(tp);')
code.append('                var cfg = mgr.GetAlarmThresholds();')
code.append('                A(cfg != null, "default not null");')
code.append('                A(cfg.Current.UpperLimit == 2.0f, "default Current==2.0");')
code.append('                A(cfg.Power.UpperLimit == 1.5f, "default Power==1.5");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                Console.WriteLine("  [PASS] Cycle 2a"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T4() {')
code.append('            Console.WriteLine("--- Cycle 2b: save and reload ---");')
code.append('            try {')
code.append('                string tp = Path.Combine(Path.GetTempPath(), "at2.json");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                var mgr = new ConfigManager(tp);')
code.append('                var cfg = mgr.GetAlarmThresholds();')
code.append('                cfg.Current.UpperLimit = 4.0f; cfg.Power.Enabled = false;')
code.append('                mgr.SaveAlarmThresholds(cfg);')
code.append('                A(File.Exists(tp), "file created");')
code.append('                var mgr2 = new ConfigManager(tp);')
code.append('                var ld = mgr2.GetAlarmThresholds();')
code.append('                A(ld.Current.UpperLimit == 4.0f, "reload Current==4.0");')
code.append('                A(ld.Power.Enabled == false, "reload Power.Enabled==false");')
code.append('                var mgr3 = new ConfigManager(tp);')
code.append('                var ar = mgr3.GetAlarmThresholds();')
code.append('                A(ar.Current.UpperLimit == 4.0f, "restart preserves Current");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                Console.WriteLine("  [PASS] Cycle 2b"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T5() {')
code.append('            Console.WriteLine("--- Cycle 2c: update ---");')
code.append('            try {')
code.append('                string tp = Path.Combine(Path.GetTempPath(), "at3.json");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                var mgr = new ConfigManager(tp);')
code.append('                var cfg = mgr.GetAlarmThresholds();')
code.append('                cfg.Current.UpperLimit = 5.0f; mgr.SaveAlarmThresholds(cfg);')
code.append('                cfg.Current.UpperLimit = 7.5f; cfg.Power.UpperLimit = 4.2f; mgr.SaveAlarmThresholds(cfg);')
code.append('                var mgr2 = new ConfigManager(tp);')
code.append('                var lt = mgr2.GetAlarmThresholds();')
code.append('                A(lt.Current.UpperLimit == 7.5f, "latest Current==7.5");')
code.append('                A(lt.Power.UpperLimit == 4.2f, "latest Power==4.2");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                Console.WriteLine("  [PASS] Cycle 2c"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T6() {')
code.append('            Console.WriteLine("--- Cycle 3a: valid values ---");')
code.append('            try {')
code.append('                A(ThresholdValidator.ValidateUpperLimit("2.0") == null, "2.0 ok");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("0.0") == null, "0.0 ok");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("999.9") == null, "999.9 ok");')
code.append('                Console.WriteLine("  [PASS] Cycle 3a"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T7() {')
code.append('            Console.WriteLine("--- Cycle 3b: invalid values ---");')
code.append('            try {')
code.append('                A(ThresholdValidator.ValidateUpperLimit("abc") != null, "abc rejected");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("") != null, "empty rejected");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("-5.0") != null, "negative rejected");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("1000.0") != null, ">999.9 rejected");')
code.append('                Console.WriteLine("  [PASS] Cycle 3b"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T8() {')
code.append('            Console.WriteLine("--- Cycle 3c: boundary ---");')
code.append('            try {')
code.append('                A(ThresholdValidator.ValidateUpperLimit("0.0") == null, "0.0 ok");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("999.9") == null, "999.9 ok");')
code.append('                A(ThresholdValidator.ValidateUpperLimit("1000.0") != null, "1000.0 rejected");')
code.append('                Console.WriteLine("  [PASS] Cycle 3c"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T9() {')
code.append('            Console.WriteLine("--- Cycle 4: enable/disable ---");')
code.append('            try {')
code.append('                var cfg = new AlarmThresholdConfig {')
code.append('                    Current = new PhaseThresholdConfig { Enabled = true, UpperLimit = 2.0f, UpperColor = "#FF0000", UpperLineStyle = "dash" },')
code.append('                    Power = new PhaseThresholdConfig { Enabled = false, UpperLimit = 1.5f, UpperColor = "#FF0000", UpperLineStyle = "dash" }')
code.append('                };')
code.append('                A(cfg.IsCurrentThresholdActive == true, "Current active");')
code.append('                A(cfg.IsPowerThresholdActive == false, "Power inactive");')
code.append('                cfg.Current.Enabled = false; cfg.Power.Enabled = true;')
code.append('                A(cfg.IsCurrentThresholdActive == false, "Current now inactive");')
code.append('                A(cfg.IsPowerThresholdActive == true, "Power now active");')
code.append('                Console.WriteLine("  [PASS] Cycle 4"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void T10() {')
code.append('            Console.WriteLine("--- Cycle 5: cancel ---");')
code.append('            try {')
code.append('                string tp = Path.Combine(Path.GetTempPath(), "at_cancel.json");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                var mgr = new ConfigManager(tp);')
code.append('                var orig = mgr.GetAlarmThresholds();')
code.append('                orig.Current.UpperLimit = 3.0f; orig.Power.UpperLimit = 2.0f;')
code.append('                mgr.SaveAlarmThresholds(orig);')
code.append('                orig.Current.UpperLimit = 999.0f;')
code.append('                var mgr2 = new ConfigManager(tp);')
code.append('                var rld = mgr2.GetAlarmThresholds();')
code.append('                A(rld.Current.UpperLimit == 3.0f, "cancel preserves Current");')
code.append('                A(rld.Power.UpperLimit == 2.0f, "cancel preserves Power");')
code.append('                if (File.Exists(tp)) File.Delete(tp);')
code.append('                Console.WriteLine("  [PASS] Cycle 5"); p++;')
code.append('            } catch (Exception ex) { Console.WriteLine("  [FAIL]: {0}", ex.Message); f++; }')
code.append('        }')
code.append('')
code.append('        static void A(bool condition, string message) {')
code.append('            if (!condition) { Console.WriteLine("    ASSERT FAIL: {0}", message); throw new Exception(message); }')
code.append('        }')
code.append('    }')
code.append('}')

# 输出到 04_tests/generated/ 目录（C# 源码目录 SwitchMonitor.Tests/ 尚未创建）
import os as _os
out_dir = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', 'generated')
_os.makedirs(out_dir, exist_ok=True)
out_path = _os.path.join(out_dir, 'AlarmThresholdTests.cs')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(code))
print(f'Test file written to: {out_path}')
